name: "Auto Merge Bot"
description: "Automatically merge PRs from GitHub"
author: "Gerard Casas Saez"

branding:
  icon: git-merge
  color: purple

inputs:
  cwd:
    description: "The path to the root folder where it should look for code owners"
    default: ""
    required: false

  merge_method:
    description: "The merge strategy to use: 'merge', 'squash' or 'rebase'"
    default: "squash"
    required: false
  assign_reviewer:
    description: "Whether to assign or not a reviewer"
    default: "true"
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
